on:
  push:
    tags:
      - '*'

name: Publish

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Load variables
        id: vars
        run: |
          echo "dotnet_version=$(dotnet --version)" >> $env:GITHUB_OUTPUT
          echo "program_data=$env:ProgramData" >> $env:GITHUB_OUTPUT
      - uses: olegtarasov/get-tag@v2-release
        id: tag_name
      - name: Cache .NET workloads
        uses: actions/cache/restore@v4
        with:
          key: dotnet-${{ runner.os }}-${{ runner.arch }}-workloads-${{ steps.vars.outputs.dotnet_version }}
          path: ${{ steps.vars.outputs.program_data }}\dotnet\workloads
      - name: Setup .NET workloads
        run: |
          dotnet workload install android ios maccatalyst macos maui
          Invoke-RestMethod 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' | Invoke-Expression
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache NuGet packages
        uses: actions/cache/restore@v4
        with:
          key: dotnet-${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}
          path: ~/.nuget/packages
      - name: Build and pack
        run: |
          $env:VERSION_SUFFIX = "${{ steps.tag_name.outputs.tag }}" -replace "^[^\-]+-?", ""
          MSBuild -restore -t:pack -p:Configuration=Release -p:PackageOutputPath=".." -v:minimal
      - name: Publish
        run: |
          dotnet nuget push FluentIcons.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
